/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.itc.programacion2.PruebaBD.vista;

import co.edu.itc.programacion2.PruebaBD.negocio.CandidatoDAO;
import co.edu.itc.programacion2.PruebaBD.vo.CandidatoVO;
import java.awt.Color;
import javax.crypto.AEADBadTagException;
import javax.swing.JOptionPane;

/**
 *
 * @author JEFE TECNICO
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloBusqueda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_acudiente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_grado = new javax.swing.JTextField();
        btb_buscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTituloBusqueda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTituloBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloBusqueda.setText("Busqueda de Candidatos");
        getContentPane().add(txtTituloBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 320, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Codigo de candidato que desea buscar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 261, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de candidato");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 261, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido del candidato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 261, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del acudiente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        txt_acudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_acudienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_acudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 261, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono del acudiente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 261, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grado a ingresar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        txt_grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gradoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 261, -1));

        btb_buscar.setText("Buscar");
        btb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 51));
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 90, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("Volver al menu inicial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/itc/programacion2/PruebaBD/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed

    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_acudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_acudienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_acudienteActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gradoActionPerformed

    private void btb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_buscarActionPerformed
        
            txt_codigo.setBackground(Color.CYAN);
            int codigo = Integer.parseInt(txt_codigo.getText());
            CandidatoDAO bdcand = new CandidatoDAO();
            CandidatoVO cand = bdcand.candidatoFindByCodigo(codigo);

            txt_nombre.setText(cand.getNombre());
            txt_apellido.setText(cand.getApellidos());
            txt_acudiente.setText(cand.getNombreAcudiente());
            txt_telefono.setText(cand.getTelefonoAcudiente());
            txt_grado.setText(cand.getGradoAIngresar());
            
    }//GEN-LAST:event_btb_buscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigo, nombre, apellido, acudiente, telefono, grado;

        codigo = txt_codigo.getText();
        nombre = txt_nombre.getText();
        apellido = txt_apellido.getText();
        acudiente = txt_acudiente.getText();
        telefono = txt_telefono.getText();
        grado = txt_grado.getText();

        CandidatoVO cand1 = new CandidatoVO(Integer.parseInt(codigo), nombre, apellido, acudiente, telefono, grado);
        CandidatoDAO bdcandidatos = new CandidatoDAO();
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea modificar el candidato?");

        if (opcion == 0) {
            bdcandidatos.actualizarCandidato(cand1);
            JOptionPane.showMessageDialog(null, "Candidato modificado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "El candidato No fue modificado");
        }
        Limpiar();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String codigo, nombre, apellido, acudiente, telefono, grado;

        codigo = txt_codigo.getText();
        nombre = txt_nombre.getText();
        apellido = txt_apellido.getText();
        acudiente = txt_acudiente.getText();
        telefono = txt_telefono.getText();
        grado = txt_grado.getText();

        CandidatoVO cand1 = new CandidatoVO(Integer.parseInt(codigo), nombre, apellido, acudiente, telefono, grado);
        CandidatoDAO bdcandidatos = new CandidatoDAO();
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea ELIMINAR el candidato?");

        if (opcion == 0) {
            bdcandidatos.eliminiarEstudiante(cand1);
            JOptionPane.showMessageDialog(null, "Candidato fue ELIMINADO correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "El candidato No fue ELIMINADO");
        }
        Limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuInicial menu = new MenuInicial();
        menu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtTituloBusqueda;
    private javax.swing.JTextField txt_acudiente;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_grado;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
public void Limpiar() {
        txt_codigo.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_acudiente.setText("");
        txt_telefono.setText("");
        txt_grado.setText("");

    }
}


